export const ALLOWED_BILLING_PRODUCTS = [
  'A001 - MCF INCORPORADOR COMPLETO',
  'A009 - MCF INCORPORADOR COMPLETO + THE CLUB',
  'A009 - MCF INCORPORADOR + THE CLUB',
  'A003 - MCF Plano Anticrise Completo',
  'A004 - MCF Plano Anticrise Básico',
  'A002 - MCF INCORPORADOR BÁSICO',
];
