-- Adicionar novas colunas de métricas se não existirem
ALTER TABLE weekly_metrics 
  ADD COLUMN IF NOT EXISTS faturamento_clint NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS incorporador_50k NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS faturamento_total NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS a010_sales INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS a010_revenue NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS custo_real NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cpl NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cplr NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ob_construir NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ob_vitalicio NUMERIC DEFAULT 0;