INSERT INTO public.webhook_endpoints (
  slug,
  name,
  description,
  origin_id,
  stage_id,
  auto_tags,
  field_mapping,
  required_fields,
  is_active
) VALUES (
  'clientdata-inside',
  'ClientData Inside',
  'Webhook para captura de dados completos do lead (ClientData) na pipeline Inside Sales',
  'e3c04f21-ba2c-4c66-84f8-b4341c826b1c',
  'd346320a-00b0-4e9f-89b6-149ad1c34061',
  ARRAY['ClientData'],
  '{
    "rendaBruta": "renda_bruta",
    "fonteRenda": "fonte_renda",
    "faixaAporte": "faixa_aporte",
    "faixaAporteDescricao": "faixa_aporte_descricao",
    "isEmpresario": "is_empresario",
    "portEmpresa": "porte_empresa",
    "esporteHobby": "esporte_hobby",
    "gostaFutebol": "gosta_futebol",
    "timeFutebol": "time_futebol",
    "precisaCapitalGiro": "precisa_capital_giro",
    "valorCapitalGiro": "valor_capital_giro",
    "objetivosPrincipais": "objetivos_principais",
    "rendaPassivaMeta": "renda_passiva_meta",
    "tempoIndependencia": "tempo_independencia",
    "imovelFinanciado": "imovel_financiado",
    "possuiConsorcio": "possui_consorcio",
    "saldoFGTS": "saldo_fgts",
    "valorInvestido": "valor_investido",
    "possuiDivida": "possui_divida",
    "possuiSeguros": "possui_seguros",
    "possuiCarro": "possui_carro",
    "interesseHolding": "interesse_holding",
    "perfilIndicacao": "perfil_indicacao"
  }'::jsonb,
  ARRAY['name'],
  true
);