
UPDATE hubla_transactions
SET sale_origin = 'launch'
WHERE sale_origin IS NULL
  AND lower(customer_email) IN (
    'olavovilela10@gmail.com',
    'harissonoliveira27@gmail.com',
    'sandrojuniores@hotmail.com',
    'engenheiroyurimonteiro@gmail.com',
    'paulo@lbastar.com.br',
    'linofernandoviveiros@gmail.com',
    'dil_903@hotmail.com',
    'alexriolargo2015@outlook.com',
    'fernandamauzer@gmail.com',
    'shssilva2016@gmail.com',
    'fabioacq10@gmail.com',
    'liga.contato@gmail.com',
    'sulymanreformas@gmail.com',
    'drpedrohquirino@gmail.com',
    'robson@roarquitetura.net',
    'viniciusevertom@hotmail.com',
    'r.966178000@gmail.com',
    'wmplastica@gmail.com',
    'brenolucas@gmail.com',
    'david@dlarconstrutora.com.br',
    'wandeeley.aragao36@gmail.com',
    'ricardson.rocha@gmail.com',
    'luzisilva1987@gmail.com',
    'alessandrosantanasouza4@gmail.com',
    'joseclerqb@gmail.com',
    'abraopericias@gmail.com',
    'fernandaholdorf@gmail.com',
    'arlan_unai45@hotmail.com',
    'thiago.vilhena@hotmail.com',
    'lincon_ferrera@hotmail.com',
    'jfmoveis@icloud.com',
    'ettorifernandes94@gmail.com',
    'gobira.thon@gmail.com',
    'alessandro.perossi@hotmail.com',
    'rodrigomoreira@harpiapecas.com.br',
    'edinho.vasques@yahoo.com.br',
    'rjcoliveira80@gmail.com',
    'chavesjunior60@gmail.com',
    'neynrap2017@gmail.com',
    'americopercinato@gmail.com',
    'wallceveras@gmail.com',
    'pedrofmanco@outlool.com.br',
    'thiago.c.machado@icloud.com',
    'augusto_landiva@hotmail.com',
    'goncalves.wesley@hotmail.com'
  );
